#+TITLE: Wonder Woman
#+AUTHOR: James D. Morgan
#+DATE: 2024-05-26
#+EMAIL: ragamuffinjim@gmail.com
* Wonder Woman

Do you ever get to overpowering urge to smack some people upside the head and tell them to read a book once in a while? I have that urge just about every time I hear some one say something akin to "Back 40 years ago we were more moral than today. The world is just falling apart." The merest hint of a phrase like that tells me that the person has NEVER read a book in their lives. They are claiming the moral high ground and yet they have obviously never read The Bible that they claim to cherish. By the by, for those who haven't partaken of the word, it is full of sex and violence and allusions to things we in polite society do not talk about.

After watching the Gal Gadot movies in which she plays Wonder Woman I did a little bit of light reading on Wonder Woman. She was created by a dude named [[https://en.wikipedia.org/wiki/William_Moulton_Marston][William Moulton Marston]] in 1940. So we're talking 84 years ago. If people 40 years ago were more moral then twice that long back people must've been on the final step to heaven, right? Now Mr Moulton was married to [[https://en.wikipedia.org/wiki/Elizabeth_Holloway_Marston][Elizabeth.]] Now, the character Wonder Woman was based on a lady named [[https://en.wikipedia.org/wiki/Olive_Byrne][Olive Byrne]], who was their [[https://en.wiktionary.org/wiki/polyamorous][/polyamorous/]] life partner. William died in 1947 and Olive and Elizabeth continued living together until Olive died in 1990.

Maybe I am a product of my time or something but as I read those those articles I am struck more by the fact that William died at the ripe old age of 54 than the polyamory. The women went on to live to 86 and 100. Hmm... makes a guy think that does.
